# Generated by Django 4.1.7 on 2023-03-10 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NaturalStones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("chemical_properties", models.TextField(max_length=255)),
                ("sem_photo", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="PhysicalProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("su_emme_kapasitesi", models.FloatField(blank=True, null=True)),
                ("efektif_su_emme", models.FloatField(blank=True, null=True)),
                ("dogal_su_icerigi", models.FloatField(blank=True, null=True)),
                ("doyma_derecesi", models.FloatField(blank=True, null=True)),
                ("kuru_yogunluk", models.FloatField(blank=True, null=True)),
                ("doymus_yogunluk", models.FloatField(blank=True, null=True)),
                ("tabii_yogunluk", models.FloatField(blank=True, null=True)),
                ("mineral_tane_yogunlugu", models.FloatField(blank=True, null=True)),
                ("efektif_porozite", models.FloatField(blank=True, null=True)),
                ("toplam_porozite", models.FloatField(blank=True, null=True)),
                ("bosluk_orani", models.FloatField(blank=True, null=True)),
                (
                    "stone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atik.naturalstones",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MechanicalProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("density", models.FloatField(blank=True, null=True)),
                ("schmidt_hardness", models.FloatField(blank=True, null=True)),
                ("indirect_tensile", models.FloatField(blank=True, null=True)),
                ("uniaxial_comp_str", models.FloatField(blank=True, null=True)),
                ("bohme", models.FloatField(blank=True, null=True)),
                ("point_load", models.FloatField(blank=True, null=True)),
                ("ultrasonic", models.FloatField(blank=True, null=True)),
                (
                    "stone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atik.naturalstones",
                    ),
                ),
            ],
        ),
    ]
