# Generated by Django 4.1.7 on 2023-03-12 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cutting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cut",
            name="cakilma_bolgesi",
        ),
    ]
