# Generated by Django 4.1.7 on 2023-03-12 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cutting", "0003_remove_cut_ka_max_min_remove_cut_kd_max_min_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cut",
            old_name="dk_min",
            new_name="kd_min",
        ),
    ]
