# Generated by Django 4.1.7 on 2023-03-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("atik", "0001_initial"),
        ("abrasive", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kesme_hizi", models.IntegerField(blank=True, null=True)),
                ("kesme_derinligi", models.FloatField()),
                ("kesme_asinma", models.FloatField()),
                ("kd_max_min", models.FloatField()),
                ("ka_max_min", models.FloatField()),
                ("kesme_genisligi", models.FloatField()),
                ("yuzey_puruzlulugu", models.FloatField()),
                ("kerf_acisi", models.FloatField()),
                ("plaka_agirlik_kaybi", models.FloatField()),
                ("cakilma_bolgesi", models.FloatField()),
                (
                    "abrasive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="abrasive.abrasives",
                    ),
                ),
                (
                    "stone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atik.naturalstones",
                    ),
                ),
            ],
        ),
    ]
