# Generated by Django 4.1.7 on 2023-05-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abrasive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abrasive", models.CharField(max_length=32)),
                ("density", models.IntegerField(blank=True, null=True)),
                ("hardness_mohs", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NaturalStone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stone", models.CharField(max_length=32)),
                ("water_absorbance", models.IntegerField(blank=True, null=True)),
                (
                    "effective_water_absorbance",
                    models.IntegerField(blank=True, null=True),
                ),
                ("natural_water_content", models.IntegerField(blank=True, null=True)),
                ("degree_of_saturation", models.IntegerField(blank=True, null=True)),
                ("dry_density", models.IntegerField(blank=True, null=True)),
                ("saturated_density", models.IntegerField(blank=True, null=True)),
                ("natural_density", models.IntegerField(blank=True, null=True)),
                ("mineral_grain_density", models.IntegerField(blank=True, null=True)),
                ("effective_porosity", models.IntegerField(blank=True, null=True)),
                ("total_porosity", models.IntegerField(blank=True, null=True)),
                ("void_ratio", models.IntegerField(blank=True, null=True)),
                ("ucs", models.IntegerField(blank=True, null=True)),
                ("its", models.IntegerField(blank=True, null=True)),
                ("plt", models.IntegerField(blank=True, null=True)),
                ("bohme", models.IntegerField(blank=True, null=True)),
                ("schmidt", models.IntegerField(blank=True, null=True)),
                ("ultrasonic_wave", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CuttingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_number", models.IntegerField(blank=True, null=True)),
                ("cutting_speed", models.IntegerField(blank=True, null=True)),
                ("cutting_depth", models.IntegerField(blank=True, null=True)),
                ("cd_stddev", models.IntegerField(blank=True, null=True)),
                ("cd_max", models.IntegerField(blank=True, null=True)),
                ("cd_min", models.IntegerField(blank=True, null=True)),
                ("wear_zone_depth", models.IntegerField(blank=True, null=True)),
                ("wz_stddev", models.IntegerField(blank=True, null=True)),
                ("wz_max", models.IntegerField(blank=True, null=True)),
                ("wz_min", models.IntegerField(blank=True, null=True)),
                ("cutting_width", models.IntegerField(blank=True, null=True)),
                ("cw_stddev", models.IntegerField(blank=True, null=True)),
                ("kerf_angle", models.IntegerField(blank=True, null=True)),
                ("material_removal_rate", models.IntegerField(blank=True, null=True)),
                ("Ra_surface_roughness", models.IntegerField(blank=True, null=True)),
                ("Ra_stddev", models.IntegerField(blank=True, null=True)),
                ("Rq_surface_roughness", models.IntegerField(blank=True, null=True)),
                ("Rq_stddev", models.IntegerField(blank=True, null=True)),
                ("Rz_surface_roughness", models.IntegerField(blank=True, null=True)),
                ("Rz_stddev", models.IntegerField(blank=True, null=True)),
                (
                    "abrasive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cutting_performance.abrasive",
                    ),
                ),
                (
                    "natural_stone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cutting_performance.naturalstone",
                    ),
                ),
            ],
        ),
    ]
