# Generated by Django 4.1.7 on 2023-05-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cutting_performance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abrasive",
            name="density",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="abrasive",
            name="hardness_mohs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="Ra_stddev",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="Ra_surface_roughness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="Rq_stddev",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="Rq_surface_roughness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="Rz_stddev",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="Rz_surface_roughness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="cd_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="cd_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="cd_stddev",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="cutting_depth",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="cutting_speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="cutting_width",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="cw_stddev",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="kerf_angle",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="material_removal_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="sample_number",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="wear_zone_depth",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="wz_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="wz_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="wz_stddev",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="bohme",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="degree_of_saturation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="dry_density",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="effective_porosity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="effective_water_absorbance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="its",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="mineral_grain_density",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="natural_density",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="natural_water_content",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="plt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="saturated_density",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="schmidt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="total_porosity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="ucs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="ultrasonic_wave",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="void_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="naturalstone",
            name="water_absorbance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
