# Generated by Django 4.1.7 on 2023-05-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cutting_performance",
            "0002_alter_abrasive_density_alter_abrasive_hardness_mohs_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuttingdata",
            name="cutting_speed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cuttingdata",
            name="sample_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
