# Generated by Django 4.1.7 on 2023-03-12 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abrasives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("chemical_properties", models.TextField(max_length=255)),
                ("sem_photo", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="AbrasiveProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("density", models.FloatField(blank=True, null=True)),
                ("hardness", models.FloatField(blank=True, null=True)),
                (
                    "abrasive",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="abrasive.abrasives",
                    ),
                ),
            ],
        ),
    ]
